FROM node:22-alpine as build
WORKDIR /app
COPY package.json ./
COPY . ./
RUN yarn install
RUN npx --yes nx run tk-santral:build --baseHref / --skip-nx-cache

FROM nginx:stable-alpine
WORKDIR /usr/share/nginx/html
COPY --from=build /app/dist/apps/tk-santral /usr/share/nginx/html
COPY config/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
