FROM node:22-alpine as build
WORKDIR /app
COPY package.json ./
COPY . ./
# RUN yarn install --frozen-lockfile --production=true
RUN npx --yes nx run lotus:build --baseHref / --skip-nx-cache

FROM nginx:stable-alpine
WORKDIR /usr/share/nginx/html
COPY --from=build /app/dist/apps/lotus /usr/share/nginx/html
COPY config/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
