# FROM node:22-alpine as build
# WORKDIR /app
# COPY package.json ./
# COPY . ./
# # RUN yarn install --frozen-lockfile --production=true
# RUN npx --yes nx run lotus:build --baseHref / --skip-nx-cache


FROM node:24-alpine AS deps
WORKDIR /app
# COPY package.json package-lock.json ./
COPY package.json ./
# TODO: NPM Registry'sinde bulunmayan paketler için mecbur koskoca node_modules klasörünü kopyalamak zorunda kaldım. Bu da build süresini uzatıyor, ama sonra bakarım...
# COPY node_modules ./node_modules
COPY decorate-angular-cli.js ./
RUN npm install --force --legacy-peer-deps --no-audit --no-fund
# COPY node_modules/@tk-postral ./node_modules/@tk-postral

FROM node:24-alpine AS build
WORKDIR /app
COPY . ./
COPY --from=deps /app/node_modules ./node_modules
RUN npx --yes nx run postral-core:build --baseHref / --skip-nx-cache
RUN npm prune --omit=dev --force --legacy-peer-deps && npm cache clean --force

# FROM node:24-alpine AS runtime
# WORKDIR /app
# ENV NODE_ENV=production
# COPY --from=build /app/dist/apps/postral-core /app
# # COPY --from=build /app/node_modules /app/node_modules
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]


FROM nginx:stable-alpine
WORKDIR /usr/share/nginx/html
COPY --from=build /app/dist/apps/admin/postral-core /usr/share/nginx/html
COPY config/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
