FROM node:24-alpine as build
WORKDIR /app
COPY . ./
# RUN yarn install --frozen-lockfile --production=true
RUN npx --yes nx run lotus-api-exams:build --skipNxCache

FROM node:24-alpine
WORKDIR /app
COPY --from=build /app/dist/apps/lotus-api/exams /app
COPY --from=build /app/node_modules /app/node_modules
EXPOSE 3333
CMD ["node", "/app/main.js"]
