/**
 * PrimeIcons → Material Symbols eşleştirme tablosu.
 * Karşılığı olmayan ikonlar için MATERIAL_FALLBACK kullanılır.
 */
export const PI_TO_MATERIAL_MAP: Record<string, string> = {
  'pi-plus': 'add',
  'pi-check': 'check',
  'pi-times': 'close',
  'pi-pencil': 'edit',
  'pi-chevron-left': 'chevron_left',
  'pi-chevron-right': 'chevron_right',
  'pi-trash': 'delete',
  'pi-eye': 'visibility',
  'pi-cog': 'settings',
  'pi-users': 'group',
  'pi-question': 'help',
  'pi-home': 'home',
  'pi-chevron-down': 'expand_more',
  'pi-sign-out': 'logout',
  'pi-download': 'download',
  'pi-save': 'save',
  'pi-play': 'play_arrow',
  'pi-comments': 'forum',
  'pi-user': 'person',
  'pi-upload': 'upload',
  'pi-send': 'send',
  'pi-exclamation-triangle': 'warning',
  'pi-chart-bar': 'bar_chart',
  'pi-reply': 'reply',
  'pi-history': 'history',
  'pi-user-plus': 'person_add',
  'pi-search': 'search',
  'pi-image': 'image',
  'pi-file': 'description',
  'pi-comment': 'comment',
  'pi-chevron-up': 'expand_less',
  'pi-book': 'menu_book',
  'pi-ban': 'block',
  'pi-align-justify': 'drag_indicator',
  'pi-sort-alt': 'swap_vert',
  'pi-sliders-v': 'tune',
  'pi-sign-in': 'login',
  'pi-refresh': 'refresh',
  'pi-lock': 'lock',
  'pi-list': 'list',
  'pi-info': 'info',
  'pi-eye-slash': 'visibility_off',
  'pi-ellipsis-h': 'more_horiz',
  'pi-copy': 'content_copy',
  'pi-code': 'code',
  'pi-clock': 'schedule',
  'pi-box': 'inventory_2',
  'pi-wifi': 'wifi',
  'pi-user-edit': 'manage_accounts',
  'pi-undo': 'undo',
  'pi-th-large': 'grid_view',
  'pi-talk': 'chat',
  'pi-tags': 'sell',
  'pi-sun': 'light_mode',
  'pi-stop': 'stop',
  'pi-star': 'star',
  'pi-sort': 'sort',
  'pi-shield': 'shield',
  'pi-moon': 'dark_mode',
  'pi-money-bill': 'payments',
  'pi-minus': 'remove',
  'pi-map-marker': 'location_on',
  'pi-key': 'key',
  'pi-info-circle': 'info',
  'pi-inbox': 'inbox',
  'pi-heart': 'favorite',
  'pi-flag': 'flag',
  'pi-external-link': 'open_in_new',
  'pi-envelope': 'mail',
  'pi-ellipsis-v': 'more_vert',
  'pi-edit': 'edit',
  'pi-earth': 'public',
  'pi-dollar': 'attach_money',
  'pi-delete': 'delete',
  'pi-credit-card': 'credit_card',
  'pi-chart-line': 'show_chart',
  'pi-caret-left': 'arrow_left',
  'pi-bot': 'smart_toy',
  'pi-bookmark': 'bookmark',
  'pi-bolt': 'bolt',
  'pi-arrow-up-right': 'north_east',
  'pi-arrows-v': 'swap_vert',
  'pi-arrow-left': 'arrow_back',
  'pi-archive': 'archive',
  'pi-spinner': 'progress_activity',
  'pi-spin': '', // animation class, handled separately
  // Sosyal medya — placeholder
  'pi-twitter': 'priority_high',
  'pi-instagram': 'priority_high',
  'pi-linkedin': 'priority_high',
  'pi-github': 'priority_high',
};

export const MATERIAL_FALLBACK = 'priority_high';
