/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can be have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2025-09-29T17:39:22.064Z
 */
import { AccountDTO, AccountSearchParamsDTO, PaymentSearchFlatDTO, RelatedAccountFilterDto } from '@tk-postral/payment-common';

import { CrudBaseServiceGenerator } from '@lotus/front-global/front-bases';
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class AccountControllerService extends CrudBaseServiceGenerator<AccountDTO, AccountDTO, AccountSearchParamsDTO>("/service/payment/api/account") {

  readonly paymentRelatedAccountsPath = "service/payment/api/payment";
  readonly sellerPaymentOrderRelatedAccountsPath = "service/payment/api/seller-payment-order";

  /**
   *
   */
  constructor(http: HttpClient) {
    super(http);
  }


  public paymentRelatedAccounts(filter?: RelatedAccountFilterDto): Observable<AccountDTO[]> {
    const url = `${this.paymentRelatedAccountsPath}/related-accounts`;
    const qp = this.queryToString(filter);
    return this.http.get<AccountDTO[]>(url + qp);
  }

}
