/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can be have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2025-09-29T17:39:22.064Z
 */
import { AccountDTO } from '@tk-postral/payment-common';


import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class AccountUserControllerService {
  readonly basePath = '/service/payment/api/current-user/account';
  constructor(private http: HttpClient) {}
  
  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }  
  


  findAll(): Observable<AccountDTO[]> {
    let urlAltered = this.interceptUrl("");

    return this.http.get<AccountDTO[]>(urlAltered);
  }


  findOne(id: string): Observable<AccountDTO> {
    let urlAltered = this.interceptUrl(":id").replace(':id', id + '');

    return this.http.get<AccountDTO>(urlAltered);
  }


  create(requestBody: AccountDTO): Observable<AccountDTO> {
    let urlAltered = this.interceptUrl("");

    return this.http.post<AccountDTO>(urlAltered, requestBody);
  }


  update(requestBody: AccountDTO): Observable<AccountDTO> {
    let urlAltered = this.interceptUrl("");

    return this.http.put<AccountDTO>(urlAltered, requestBody);
  }


  remove(id: string): Observable<void> {
    let urlAltered = this.interceptUrl(":id").replace(':id', id + '');

    return this.http.delete<void>(urlAltered);
  }


}
