/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can be have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 */
import { AdminSettingsDto } from '@tk-postral/payment-common';

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class AdminSettingsControllerService {
  readonly basePath = '/service/payment/api/admin-settings';

  constructor(private http: HttpClient) {}

  interceptUrl(url: string): string {
    return this.basePath + (!url || this.basePath.endsWith('/') ? '' : '/') + url;
  }

  getAdminSettings(): Observable<AdminSettingsDto> {
    const urlAltered = this.interceptUrl('');

    return this.http.get<AdminSettingsDto>(urlAltered);
  }

  updateAdminSettings(
    requestBody: Partial<AdminSettingsDto>
  ): Observable<AdminSettingsDto> {
    const urlAltered = this.interceptUrl('');

    return this.http.put<AdminSettingsDto>(urlAltered, requestBody);
  }
}