/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can be have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2025-09-29T17:39:22.064Z
 */
import { AppComissionDTO } from '@tk-postral/payment-common';


import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class AppComissionControllerService {
  readonly basePath = '/service/payment/api/app-comission';
  constructor(private http: HttpClient) {}
  
  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }  

  findAll(): Observable<AppComissionDTO[]> {
    let urlAltered = this.interceptUrl("");

    return this.http.get<AppComissionDTO[]>(urlAltered);
  }


  update(requestBody: AppComissionDTO): Observable<AppComissionDTO> {
    let urlAltered = this.interceptUrl("");

    return this.http.put<AppComissionDTO>(urlAltered, requestBody);
  }

  removeById(id: string): Observable<void> {
    let urlAltered = this.interceptUrl(id);

    return this.http.delete<void>(urlAltered);
  }


}
