/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can be have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-08-09T13:15:19.402Z
 */
import { SearchResult } from '@ubs-platform/crud-base-common';
import { ExternalPlatformDTO } from '@tk-postral/payment-common';


import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class ExternalPlatformControllerService {
  readonly basePath = '/service/payment';
  constructor(private http: HttpClient) {}
  
  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }  
  
  // TODO: Eğer requestBody void ise parametreye ekleme!


  findAllSearch(page: number, size: number, sortBy: string | undefined, sortRotation: "desc" | "asc" | undefined, requestBody: void): Observable<SearchResult<ExternalPlatformDTO>> {
    let urlAltered = this.interceptUrl("api/external-platform/_search") + '?' + `page=${page}` + '&' + `size=${size}` + '&' + `sortBy=${sortBy}` + '&' + `sortRotation=${sortRotation}`;

    return this.http.get<SearchResult<ExternalPlatformDTO>>(urlAltered);
  }


  update(requestBody: ExternalPlatformDTO): Observable<ExternalPlatformDTO> {
    let urlAltered = this.interceptUrl("api/external-platform");

    return this.http.put<ExternalPlatformDTO>(urlAltered, requestBody);
  }


  delete(id: string): Observable<void> {
    let urlAltered = this.interceptUrl("api/external-platform/:id").replace(':id', id + '');

    return this.http.delete<void>(urlAltered);
  }


}
