/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can be have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-02-15T11:39:05.711Z
 */
import { InvoiceCreateDTO, InvoiceDTO, InvoiceSearchDTO, InvoiceUpdateDTO } from '@tk-postral/payment-common';


import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { SearchResult } from '@ubs-platform/crud-base-common';

@Injectable({
  providedIn: 'root'
})
export class InvoiceControllerService {
  readonly basePath = '/service/payment/api/invoice';
  constructor(private http: HttpClient) {}
  

  fetchAll(s: InvoiceSearchDTO): Observable<InvoiceDTO[]> {
    let urlAltered = this.interceptUrl("");
    return this.http.get<InvoiceDTO[]>(urlAltered, { params: s as any });
  }

  search(s: InvoiceSearchDTO): Observable<SearchResult<InvoiceDTO>> {
    let urlAltered = this.interceptUrl("/_search");
    return this.http.get<SearchResult<InvoiceDTO>>(urlAltered, { params: s as any });
  }

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }  
  


  create(requestBody: InvoiceCreateDTO): Observable<InvoiceDTO> {
    let urlAltered = this.interceptUrl("");

    return this.http.post<InvoiceDTO>(urlAltered, requestBody);
  }


  findById(id: string): Observable<InvoiceDTO> {
    let urlAltered = this.interceptUrl(":id").replace(':id', id + '');

    return this.http.get<InvoiceDTO>(urlAltered);
  }


  update(id: string, requestBody: InvoiceUpdateDTO): Observable<InvoiceDTO> {
    let urlAltered = this.interceptUrl(":id").replace(':id', id + '');

    return this.http.put<InvoiceDTO>(urlAltered, requestBody);
  }


  delete(id: string): Observable<void> {
    let urlAltered = this.interceptUrl(":id").replace(':id', id + '');

    return this.http.delete<void>(urlAltered);
  }


  finalize(id: string): Observable<InvoiceDTO> {
    let urlAltered = this.interceptUrl(":id/finalize").replace(':id', id + '');

    return this.http.put<InvoiceDTO>(urlAltered, null);
  }


  createFromTransaction(sellerPaymentOrderId: string): Observable<InvoiceDTO> {
    let urlAltered = this.interceptUrl("/from-transaction/:sellerPaymentOrderId").replace(':sellerPaymentOrderId', sellerPaymentOrderId + '');

    return this.http.post<InvoiceDTO>(urlAltered, null);
  }


  downloadUblUrl(id: string) {
    let url = this.interceptUrl(":id/ubl").replace(':id', id + '');
    this.http.get(url, { observe: 'response', responseType: 'blob' }).subscribe(response => {
      if (response.status !== 200) {
        alert('UBL dosyası indirilemedi. Lütfen tekrar deneyiniz.');
        return;
      }
      if (!response.body) {
        alert('UBL dosyası bulunamadı.');
        return;
      }
      const url = window.URL.createObjectURL(response.body);
      const a = document.createElement('a');
      a.href = url;
      a.download = `invoice_${id}.xml`;
      a.click();
      window.URL.revokeObjectURL(url);
    });
    // return this.interceptUrl(":id/ubl").replace(':id', id + '');
  }


}
