/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can be have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2025-09-29T17:39:22.064Z
 */
import { ItemDTO, ItemPriceDTO } from '@tk-postral/payment-common';


import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class ItemAdminControllerService {
  readonly basePath = '/service/payment/api/item';
  constructor(private http: HttpClient) {}
  
  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }  
  


  findAll(id: string | undefined, entityGroup: string | undefined, entityName: string | undefined, entityId: string | undefined): Observable<ItemDTO[]> {
    let urlAltered = this.interceptUrl("") + '?' + `id=${id}` + '&' + `entityGroup=${entityGroup}` + '&' + `entityName=${entityName}` + '&' + `entityId=${entityId}`;

    return this.http.get<ItemDTO[]>(urlAltered);
  }


  findOne(id: string): Observable<ItemDTO> {
    let urlAltered = this.interceptUrl(":id").replace(':id', id + '');

    return this.http.get<ItemDTO>(urlAltered);
  }


  create(requestBody: ItemDTO): Observable<ItemDTO> {
    let urlAltered = this.interceptUrl("");

    return this.http.post<ItemDTO>(urlAltered, requestBody);
  }


  setPrice(itemId: string, requestBody: ItemPriceDTO): Observable<ItemPriceDTO> {
    let urlAltered = this.interceptUrl(":itemId/price").replace(':itemId', itemId + '');

    return this.http.put<ItemPriceDTO>(urlAltered, requestBody);
  }


  getDefaultPrice(itemId: string, variation: string | undefined, currency: string, region: string): Observable<ItemPriceDTO[]> {
    let urlAltered = this.interceptUrl(":itemId/price/default").replace(':itemId', itemId + '') + '?' + `variation=${variation}` + '&' + `currency=${currency}` + '&' + `region=${region}`;

    return this.http.get<ItemPriceDTO[]>(urlAltered);
  }


  getLatestPrice(itemId: string, variation: string | undefined, currency: string, region: string): Observable<ItemPriceDTO[]> {
    let urlAltered = this.interceptUrl(":itemId/price/latest").replace(':itemId', itemId + '') + '?' + `variation=${variation}` + '&' + `currency=${currency}` + '&' + `region=${region}`;

    return this.http.get<ItemPriceDTO[]>(urlAltered);
  }


  update(requestBody: ItemDTO): Observable<ItemDTO> {
    let urlAltered = this.interceptUrl("");

    return this.http.put<ItemDTO>(urlAltered, requestBody);
  }


  remove(id: string): Observable<void> {
    let urlAltered = this.interceptUrl(":id").replace(':id', id + '');

    return this.http.delete<void>(urlAltered);
  }


}
