/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can be have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2025-09-29T17:39:22.064Z
 */
import { AccountDTO, AccountSearchParamsDTO, ItemDTO, ItemSearchDTO, ItemTaxDTO, ItemTaxSearchDTO } from '@tk-postral/payment-common';

import { CrudBaseServiceGenerator } from '@lotus/front-global/front-bases';
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class ItemTaxControllerService extends CrudBaseServiceGenerator<ItemTaxDTO, ItemTaxDTO, ItemTaxSearchDTO>("/service/payment/api/item-tax") {
  /**
   *
   */
  constructor(http: HttpClient) {
    super(http);

  }

}
