/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can be have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2025-09-29T17:39:22.064Z
 */
import {
  AccountDTO,
  AccountSearchParamsDTO,
  ItemDTO,
  ItemPriceDTO,
  ItemSearchDTO,
} from '@tk-postral/payment-common';

import { CrudBaseServiceGenerator } from '@lotus/front-global/front-bases';
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class ItemCrudService extends CrudBaseServiceGenerator<
  ItemDTO,
  ItemDTO,
  ItemSearchDTO
>('/service/payment/api/item') {
  /**
   *
   */
  constructor(http: HttpClient) {
    super(http);
  }

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.baseUrl + (!url || this.baseUrl.endsWith('/') ? '' : '/') + url;
  }

  getLatestPrices(id: string): Observable<ItemPriceDTO[]> {
    let urlAltered = this.interceptUrl(':id/prices/latest').replace(
      ':id',
      id + ''
    );

    return this.http.get<ItemPriceDTO[]>(urlAltered);
  }

  getDefaultPrices(id: string): Observable<ItemPriceDTO[]> {
    let urlAltered = this.interceptUrl(':id/prices/default').replace(
      ':id',
      id + ''
    );

    return this.http.get<ItemPriceDTO[]>(urlAltered);
  }

  updateDefaultPrice(priceDto: ItemPriceDTO): Observable<ItemPriceDTO> {
    let urlAltered = this.interceptUrl(':id/prices/default').replace(
      ':id',
      priceDto.itemId + ''
    );

    return this.http.post<ItemPriceDTO>(urlAltered, priceDto);
  }

  removePrice(itemId: string, priceId: string): Observable<void> {
    let urlAltered = this.interceptUrl(':id/prices/:priceId')
      .replace(':id', itemId + '')
      .replace(':priceId', priceId + '');

    return this.http.delete<void>(urlAltered);
  }
}
