/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can be have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2025-09-29T17:39:22.064Z
 */
import {
  PaymentTransactionDTO,
  PaymentItemSearchDTO,
  PaymentItemDto,
} from '@tk-postral/payment-common';

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class PaymentItemSearchService {
  readonly basePath = '/service/payment/api/payment-items';
  constructor(private http: HttpClient) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return (
      this.basePath + (!url || this.basePath.endsWith('/') ? '' : '/') + url
    );
  }

  fetchPaymentItems(filter: PaymentItemSearchDTO): Observable<PaymentItemDto[]> {
    let urlAltered = this.interceptUrl("");

    return this.http.get<PaymentItemDto[]>(urlAltered, { params: filter as any });
  }

}
