/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can be have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2025-09-29T17:39:22.064Z
 */
import {
  ItemPriceDTO,
  ReportDTO,
  ReportFullDTO,
  ReportQueryDTO,
  ReportQuerySearchDTO,ReportSearchPaginationDTO
} from '@tk-postral/payment-common';

import { CrudBaseServiceGenerator } from '@lotus/front-global/front-bases';
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { SearchResult } from '@ubs-platform/crud-base-common';

@Injectable({
  providedIn: 'root',
})
export class ReportControllerService {
  readonly baseUrl = '/service/payment/api/report';
  constructor(private http: HttpClient) {
  }

  reconstructReports(reportId: string, findNotExistingPaymentsForAccountId = false): Observable<ReportDTO[]> {
    return this.http.post<ReportDTO[]>(`${this.baseUrl}/reconstruct`, { findNotExistingPaymentsForAccountId, reportId });
  }

  fetchInProgressReportIds(reportIds: string[]): Observable<{[reportId: string]: string}> {
    return this.http.post<{[reportId: string]: string}>(`${this.baseUrl}/fetch-in-progress`, { reportIds });
  }

  getReportById(id: string): Observable<ReportFullDTO> {
    return this.http.get<ReportFullDTO>(`${this.baseUrl}/${id}`);
  }

  searchReports(q: ReportSearchPaginationDTO): Observable<SearchResult<ReportDTO>> {
    return this.http.get<SearchResult<ReportDTO>>(`${this.baseUrl}/_search`, { params: q as any });
  }
}
