/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can be have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2025-09-29T17:39:22.064Z
 */
import {
  ItemPriceDTO,
  ReportDTO,
  ReportQueryDTO,
  ReportQuerySearchDTO,
} from '@tk-postral/payment-common';

import { CrudBaseServiceGenerator } from '@lotus/front-global/front-bases';
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class ReportQueryControllerService extends CrudBaseServiceGenerator<
  ReportQueryDTO,
  ReportQueryDTO,
  ReportQuerySearchDTO
>('/service/payment/api/report-query') {

  constructor(http: HttpClient) {
    super(http);
  }

  getReports(queryId: string): Observable<ReportDTO[]> {
    return this.http.get<ReportDTO[]>(`/service/payment/api/report-query/${queryId}/reports`);
  }
}
