/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can be have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2025-09-29T17:39:22.064Z
 */
import {
  PaymentInitDTO,
  PaymentDTO,
  PaymentCaptureInfoDTO,
  PaymentItemDto,
  TaxDTO,
  PaymentChannelStatusDTO,
  PaymentTransactionSearchPaginationDTO,
  PaymentTransactionDTO,
} from '@tk-postral/payment-common';

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class TransactionControllerService {
  readonly basePath = '/service/payment/api/seller-payment-order';
  constructor(private http: HttpClient) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return (
      this.basePath + (!url || this.basePath.endsWith('/') ? '' : '/') + url
    );
  }

  searchTransactions(filter: PaymentTransactionSearchPaginationDTO): Observable<PaymentTransactionDTO[]> {
    let urlAltered = this.interceptUrl('/_search');

    return this.http.get<PaymentTransactionDTO[]>(urlAltered, { params: filter as any });
  }

  fetchById(id: string): Observable<PaymentTransactionDTO> {
    let urlAltered = this.interceptUrl('/:id').replace(':id', id + '');
    return this.http.get<PaymentTransactionDTO>(urlAltered);
  }

  // initialize(requestBody: PaymentInitDTO): Observable<PaymentDTO> {
  //   let urlAltered = this.interceptUrl('');

  //   return this.http.post<PaymentDTO>(urlAltered, requestBody);
  // }

  // checkOperation(id: string): Observable<PaymentDTO> {
  //   let urlAltered = this.interceptUrl('/:id/operation/check').replace(
  //     ':id',
  //     id + ''
  //   );

  //   return this.http.post<PaymentDTO>(urlAltered, null);
  // }

  // startPayment(
  //   id: string,
  //   requestBody: PaymentCaptureInfoDTO
  // ): Observable<PaymentChannelStatusDTO> {
  //   let urlAltered = this.interceptUrl('/:id/operation/start').replace(
  //     ':id',
  //     id + ''
  //   );

  //   return this.http.post<PaymentChannelStatusDTO>(urlAltered, requestBody);
  // }

  // fetchAll(): Observable<PaymentDTO[]> {
  //   let urlAltered = this.interceptUrl('');

  //   return this.http.get<PaymentDTO[]>(urlAltered);
  // }

  // fetchPaymentInformation(id: string): Observable<PaymentDTO> {
  //   let urlAltered = this.interceptUrl('/:id').replace(':id', id + '');

  //   return this.http.get<PaymentDTO>(urlAltered);
  // }

  // fetchItems(id: string): Observable<PaymentItemDto[]> {
  //   let urlAltered = this.interceptUrl('/:id/item').replace(':id', id + '');

  //   return this.http.get<PaymentItemDto[]>(urlAltered);
  // }

  // fetchTaxes(id: string): Observable<TaxDTO[]> {
  //   let urlAltered = this.interceptUrl('/:id/tax').replace(':id', id + '');

  //   return this.http.get<TaxDTO[]>(urlAltered);
  // }

  // cancelPayment(id: string): Observable<void> {
  //   let urlAltered = this.interceptUrl('/:id').replace(':id', id + '');

  //   return this.http.delete<void>(urlAltered);
  // }

  // subscribePaymentStatusStream(
  //   id: string
  // ): Observable<MessageEvent<PaymentDTO>> {
  //   let urlAltered = this.interceptUrl('/:id/operation/stream').replace(
  //     ':id',
  //     id + ''
  //   );

  //   return new Observable<MessageEvent<PaymentDTO>>((observer) => {
  //     const eventSource = new EventSource(urlAltered);

  //     eventSource.onmessage = (event) => {
  //       observer.next(event);
  //     };

  //     eventSource.onerror = (error) => {
  //       observer.error(error);
  //       eventSource.close();
  //     };

  //     return () => {
  //       eventSource.close();
  //     };
  //   });
  // }
}
