/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can be have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2025-10-14T11:00:26.301Z
 */
import {
  EOGUserCapabilityDTO,
  EOGUserCapabilityInvitationDTO,
  EOGUserCapabilityInviteDTO,
  EntityOwnershipGroupDTO,
} from '@ubs-platform/users-common';

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class EntityOwnershipGroupControllerService {
  readonly basePath = '/api/users/entity-ownership-group';
  constructor(private http: HttpClient) { }

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return (
      this.basePath + (!url || this.basePath.endsWith('/') ? '' : '/') + url
    );
  }

  fetchUserCapabilityInvitations(id: string): Observable<EOGUserCapabilityInvitationDTO[]> {
    let urlAltered = this.interceptUrl(":id/invitation").replace(':id', id + '');

    return this.http.get<EOGUserCapabilityInvitationDTO[]>(urlAltered);
  }

  removeUserFromEntityOwnershipInvitation(id: string, invitationId: string): Observable<void> {
    let urlAltered = this.interceptUrl(":id/invitation/:invitationId").replace(':id', id + '').replace(':invitationId', invitationId + '');

    return this.http.delete<void>(urlAltered);
  }


  refuseInvitation(invitationId: string): Observable<void> {
    let urlAltered = this.interceptUrl("invitation/:invitationId").replace(':invitationId', invitationId + '');

    return this.http.delete<void>(urlAltered);
  }



  addUserToEntityOwnership(id: string, requestBody: EOGUserCapabilityInviteDTO): Observable<void> {
    let urlAltered = this.interceptUrl(":id/invitation").replace(':id', id + '');

    return this.http.post<void>(urlAltered, requestBody);
  }


  acceptInvitationToEog(inviteId: string): Observable<void> {
    let urlAltered = this.interceptUrl("invitation/:inviteId").replace(':inviteId', inviteId + '');

    return this.http.post<void>(urlAltered, null);
  }

  editUserCapabilityEntityOwnership(id: string, cap : EOGUserCapabilityDTO): Observable<void> {
    let urlAltered = this.interceptUrl(':id/capability')
      .replace(':id', id + '');

    return this.http.put<void>(urlAltered, cap);
  }


  removeUserFromEntityOwnership(id: string, userId: string): Observable<void> {
    let urlAltered = this.interceptUrl(':id/capability/:userId')
      .replace(':id', id + '')
      .replace(':userId', userId + '');

    return this.http.delete<void>(urlAltered);
  }

  fetchUsersInGroup(id: string): Observable<EOGUserCapabilityDTO[]> {
    let urlAltered = this.interceptUrl(':id/users').replace(':id', id + '');

    return this.http.get<EOGUserCapabilityDTO[]>(urlAltered);
  }

  fetchMyInvitations(): Observable<EOGUserCapabilityInvitationDTO[]> {
    let urlAltered = this.interceptUrl("invitation/_currentuser");

    return this.http.get<EOGUserCapabilityInvitationDTO[]>(urlAltered);
  }

}
